### ISSUE TITLE
超帥! 但是我也想要英文字母!

### ISSUE THREAD

**Issue by Ahtram** [justfont/Elffont#1]
感謝做出這麼棒的字體!

小弟非常想要將它用在個人製作的遊戲內，不知能否支援一下加入英文字母跟常用符號呢?
可以的話應該可以讓大多數的人都在遊戲內打出精靈文 XD

**Comment by rutopio** [comment]
關於擴充一事，這還需要另外得到 [做作的Daphne](https://www.facebook.com/dramadaphne) 老師的支持。

不過，市面上已有許多類似風格的歐文字型，
你可以嘗試搜尋「歌德體 (Blackletter Fonts)」（配合岩的造型），
或是「卡洛林小寫體 (Carolingian Fonts)」（配合蕨的造型）來購買使用。
