### ISSUE TITLE
聲符位置的疑問 

### ISSUE THREAD

**Issue by Hortjim** [justfont/Elffont#2]
用注音輸入時聲符要怎麼像轉換器那樣在正上方呢?

**Comment by justfontcom** [comment]
正常輸入注音即可，像是 `ㄓㄜˋㄧㄤˋ`。

聲調是透過 Opentype 的「[字符分解與組合（Glyph Composition / Decomposition, *abbr.* 'ccmp'）](https://learn.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-ccmp)」特性和韻母結合的，
像是 Office Word, Pages, Adobe Illustrator 和 Photoshop 等主流文書與設計軟體應該都有支援顯示。

另外，如果要用在網頁上的話，雖然多數瀏覽器預設都是啟用，但也可以額外透過 css 確保該特性的調用：

```
.className {
  -moz-font-feature-settings: "ccmp";
  -webkit-font-feature-settings: "ccmp";
  font-feature-settings: "ccmp";
}
```

如果排版引擎沒有支援該特性的話，則聲調僅會貼齊韻母的右側，而非置於韻母之上。

**Comment by Hortjim** [comment]
![image](https://github.com/user-attachments/assets/70b38648-eb19-45aa-b924-d73872209bac)
大概就像這樣子會在"字"中間 (補充：這是ppt內文字框輸入的結果)

**Comment by rutopio** [comment]
使用時只要正常輸入注音即可，像是 `ㄓㄜˋㄧㄤˋ`。

聲調是透過 [Opentype 的「字符分解與組合」(Glyph Composition / Decomposition, abbr. *ccmp*) 特性](https://learn.microsoft.com/en-us/typography/opentype/spec/features_ae#tag-ccmp)與韻母結合的，
主流的文書與設計軟體，如 Office Word, Pages, Adobe Illustrator & Photoshop 都有支援該特性，
而瀏覽器如 Safari (Webkit-based) Chrome (Blink-based) 亦有支援，但也可以透過 css 強制指定：

.className {
  -moz-font-feature-settings: "ccmp";
  -webkit-font-feature-settings: "ccmp";
  font-feature-settings: "ccmp";
}

如果你所使用的軟體排版引擎沒有支援該特性、或是沒有特別調用的話，
則聲調僅會貼齊韻母的右側（如你的附圖所示），而非置於韻母之上。

**Comment by rutopio** [comment]
補充：

我剛剛測試過 MacOs 版本的 PowerPoint 2019 在處理 [jf 粉圓](https://github.com/justfont/open-huninn-font)的臺客羅馬拼音是能正常調用 ccmp 特性的，
但精靈文的聲調會出現問題。

而另外一台電腦上的 Windows PowerPoint 2016 則是臺客羅馬拼音與精靈文兩者皆無法正確地顯示。

可見不同版本的 Office PowerPoint 在是否支援 ccmp 特性上，存在歧異或是不完全，
如果要用的話，可以使用我們官網的[「精靈文字體轉換器」](https://justfont.com/justforfun/elf-bpmf)來生成透明背景的 png，再貼到投影片內。
